CUPBOARD_ASSET = "assets/cupboard.png"
FLOOR_ASSET = "assets/floor.png"
OVEN_ASSET = "assets/oven.png"
SINK_ASSET = "assets/sink.png"
ANIMATION_ASSET = "assets/animations/"
MALE_CHAR_ASSET = ANIMATION_ASSET + "S_M/S0.png"
FEMALE_CHAR_ASSET = ANIMATION_ASSET + "S_F/S0.png"