CUPBOARD_ASSET = "assets/cupboard.png"
FLOOR_ASSET = "assets/floor.png"
OVEN_ASSET = "assets/oven.png"
SINK_ASSET = "assets/sink.png"
MALE_CHAR_ASSET = "assets/temp_character_M.jpeg"
FEMALE_CHAR_ASSET = "assets/temp_character_F.jpeg"